# Generated by Django 3.2.9 on 2022-01-14 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuario.models
import usuario.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('rol', models.CharField(choices=[('VOLUNTARIO', 'VOLUNTARIO'), ('ORGANIZADOR', 'ORGANIZADOR'), ('USUARIO REGISTRADO', 'USUARIO REGISTRADO'), ('SUPERUSUARIO', 'SUPERUSUARIO')], max_length=255, verbose_name='Roles')),
                ('fecha_reg', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Estado Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Estado superusuario')),
                ('is_organizador', models.BooleanField(default=False, verbose_name='Estado Organizador')),
                ('is_voluntario', models.BooleanField(default=False, verbose_name='Estado voluntario')),
                ('is_userr', models.BooleanField(default=False, verbose_name='Estado usuario registrado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'User',
            },
            managers=[
                ('objects', usuario.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='Usuario', max_length=255)),
                ('Apellido', models.CharField(default='Invitado', max_length=255)),
                ('Carnet', models.IntegerField(default=0)),
                ('Extencion', models.CharField(choices=[('LA PAZ', 'LA PAZ'), ('ORURO', 'ORURO'), ('POTOSI', 'POTOSI'), ('COCHABAMBA', 'COCHABAMBA'), ('BENI', 'BENI'), ('SANTA CRUZ', 'SANTA CRUZ'), ('PANDO', 'PANDO'), ('TARIJA', 'TARIJA'), ('SUCRE', 'SUCRE')], default='ninguno', max_length=255)),
                ('Genero', models.CharField(choices=[('NoDefinido', 'NoDefinido'), ('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], default='NoDefinido', max_length=20)),
                ('Fecha_Nac', models.DateField(default='2021-01-01')),
                ('Telefono', models.IntegerField(blank=True, null=True)),
                ('Celular', models.IntegerField(default=0)),
                ('Departamento', models.CharField(choices=[('LA PAZ', 'LA PAZ'), ('ORURO', 'ORURO'), ('POTOSI', 'POTOSI'), ('COCHABAMBA', 'COCHABAMBA'), ('BENI', 'BENI'), ('SANTA CRUZ', 'SANTA CRUZ'), ('PANDO', 'PANDO'), ('TARIJA', 'TARIJA'), ('SUCRE', 'SUCRE')], default='LA PAZ', max_length=255)),
                ('Ciudad', models.CharField(default='vacio', max_length=255)),
                ('Dir_zona', models.CharField(default='vacio', max_length=255)),
                ('Dir_calleOt', models.CharField(default='vacio', max_length=255)),
                ('Dir_num', models.IntegerField(default=0)),
                ('Edif', models.CharField(blank=True, max_length=100, null=True)),
                ('Dep', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'DatosPersonales',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomorganizacion', models.CharField(max_length=255, unique=True, verbose_name='Nombre Organizacion')),
                ('abreviacion', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(choices=[('LA PAZ', 'LA PAZ'), ('ORURO', 'ORURO'), ('POTOSI', 'POTOSI'), ('COCHABAMBA', 'COCHABAMBA'), ('BENI', 'BENI'), ('SANTA CRUZ', 'SANTA CRUZ'), ('PANDO', 'PANDO'), ('TARIJA', 'TARIJA'), ('SUCRE', 'SUCRE')], max_length=150)),
                ('ciudad', models.CharField(max_length=150)),
                ('fechaCreacion', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('otraRedSocial', models.URLField(blank=True)),
                ('whatsapp', models.IntegerField()),
                ('nombreContacto', models.CharField(max_length=255)),
                ('contacto2', models.IntegerField()),
                ('nombreContacto2', models.CharField(max_length=255, null=True)),
                ('fotografia', models.ImageField(upload_to=usuario.models.fotoLogo)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=25)),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'Organizacion',
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('retirado', models.BooleanField(default=False)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('avatar', models.ImageField(blank=True, default='img/Vol.png', null=True, upload_to=usuario.upload.fotoVoluntarios)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.organizacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voluntario_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
                'db_table': 'Voluntario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('avatar', models.ImageField(blank=True, default='img/User.png', null=True, upload_to=usuario.upload.fotoUsuarioReg)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuarioReg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UsuarioRegistrado',
                'verbose_name_plural': 'UsuariosRegistrados',
                'db_table': 'UsuariosReg',
            },
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('avatar', models.ImageField(blank=True, default='img/Admi.png', null=True, upload_to=usuario.upload.fotoSuperUsuario)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SuperUser_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SuperUser',
                'verbose_name_plural': 'SuperUsers',
                'db_table': 'SuperUser',
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('avatar', models.ImageField(blank=True, default='img/OR.png', null=True, upload_to=usuario.upload.fotoVoluntarios)),
                ('organizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.organizacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
                'db_table': 'Organizador',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.datospersonales'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
