# Generated by Django 3.2.9 on 2022-01-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edadAnos', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)])),
                ('edadMeses', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)])),
                ('edad_anim', models.CharField(blank=True, max_length=100)),
                ('especie_anim', models.CharField(blank=True, max_length=100)),
                ('raza_anim', models.CharField(blank=True, max_length=100)),
                ('tamano_anim', models.CharField(choices=[('PEQUEÑO', 'PEQUEÑO'), ('MEDIANO', 'MEDIANO'), ('GRANDE', 'GRANDE'), ('GIGANTE', 'GIGANTE')], max_length=100)),
                ('sexo_anim', models.CharField(choices=[('HEMBRA', 'HEMBRA'), ('MACHO', 'MACHO')], max_length=100)),
                ('color_prin', models.CharField(blank=True, max_length=100)),
                ('color_sec', models.CharField(blank=True, max_length=100)),
                ('esterilizacion', models.BooleanField(default=False)),
                ('Tipodiscapacidad', models.CharField(blank=True, choices=[('NINGUNO', 'NINGUNO'), ('FISICA', 'FISICA'), ('AUDITIVA', 'AUDITIVA'), ('VISUAL', 'VISUAL'), ('OLFATIVA', 'OLFAVITA'), ('VOCAL', 'VOCAL'), ('MULTIPLE', 'MULTIPLE')], max_length=255)),
                ('f_rescate', models.DateField()),
                ('f_adopcion', models.DateField()),
                ('diasEnAdop', models.IntegerField()),
                ('tipoIngreso', models.CharField(choices=[('RESCATE', 'RESCATE'), ('NACIDO EN LA ORGANIZACIÓN', 'NACIDO EN LA ORGANIZACIÓN'), ('ABANDONO EN CAMPAÑA/FERIA', 'ABANDONO EN CAMPAÑA/FERIA'), ('RECEPCION EN CAMPAÑA/FERIA', 'RECEPCION EN CAMPAÑA/FERIA'), ('AYUDA PARA ENCONTRAR HOGAR', 'AYUDA PARA ENCONTRAR HOGAR'), ('OTRO', 'OTRO')], default='RESCATE', max_length=100)),
                ('edad_adop', models.IntegerField()),
                ('rangoEdad', models.CharField(choices=[('ADOLECENTE', 'ADOLECENTE'), ('JOVEN', 'JOVEN'), ('ADULTO JOVEN', 'ADULTO JOVEN'), ('ADULTEZ PRIMARIA', 'ADULTEZ PRIMARIA'), ('ADULTEZ INTERMEDIA', 'ADULTEZ INTERMEDIA'), ('ADULTEZ TARDIA', 'ADULTEZ TARDIA'), ('ADULTO MAYOR', 'ADULTO MAYOR')], max_length=255)),
                ('sexo_adop', models.CharField(blank=True, choices=[('NoDefinido', 'NoDefinido'), ('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], max_length=100)),
                ('ocupacion', models.CharField(blank=True, max_length=255)),
                ('tipo_vivienda_adop', models.CharField(blank=True, choices=[('CASA PROPIA', 'CASA PROPIA'), ('CASA ALQUILER', 'CASA ALQUILER'), ('DEPARTAMENTO PROPIO', 'DEPARTAMENTO PROPIO'), ('DEPARTAMENTO ALQUILADO', 'DEPARTAMENTO ALQUILADO'), ('GARZONIER', 'GARZONIER'), ('OTRO', 'OTRO')], max_length=100)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'db_table': 'Dataset',
            },
        ),
        migrations.CreateModel(
            name='Form_C_preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('edad_per', models.IntegerField(choices=[(18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)])),
                ('sex_per', models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], max_length=255)),
                ('edad_can', models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('CACHORRO LACTANTE', 'CACHORRO LACTANTE'), ('CACHORRO', 'CACHORRO'), ('JOVEN', 'JOVEN'), ('ADULTO', 'ADULTO'), ('ADULTO SENIOR', 'ADULTO SENIOR')], max_length=255)),
                ('tamano_can', models.CharField(choices=[('PEQUEÑO', 'PEQUEÑO'), ('MEDIANO', 'MEDIANO'), ('GRANDE', 'GRANDE'), ('GIGANTE', 'GIGANTE')], max_length=255)),
                ('sexo_can', models.CharField(choices=[('HEMBRA', 'HEMBRA'), ('INDIFERENTE', 'INDIFERENTE'), ('MACHO', 'MACHO')], max_length=255)),
                ('dispnib_tiempo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)])),
                ('ninos_menores', models.BooleanField(default=False)),
                ('otro_can', models.BooleanField(default=False)),
                ('otro_gato', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Formulario_Con_Preferencias',
                'verbose_name_plural': 'Formularios_Con_Preferencias',
                'db_table': 'Form_C_Prefer',
            },
        ),
        migrations.CreateModel(
            name='Form_S_preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('edad_can', models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('CACHORRO LACTANTE', 'CACHORRO LACTANTE'), ('CACHORRO', 'CACHORRO'), ('JOVEN', 'JOVEN'), ('ADULTO', 'ADULTO'), ('ADULTO SENIOR', 'ADULTO SENIOR')], max_length=40)),
                ('tipoVivienda', models.CharField(choices=[('CASA PROPIA', 'CASA PROPIA'), ('CASA ALQUILER', 'CASA ALQUILER'), ('DEPARTAMENTO PROPIO', 'DEPARTAMENTO PROPIO'), ('DEPARTAMENTO ALQUILADO', 'DEPARTAMENTO ALQUILADO'), ('GARZONIER', 'GARZONIER'), ('OTRO', 'OTRO')], max_length=255)),
                ('edad_persona', models.IntegerField(choices=[(18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)])),
                ('sexo_persona', models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], max_length=20)),
                ('disp_tiempo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)])),
                ('ninos_menores', models.BooleanField(default=False)),
                ('otro_can', models.BooleanField(default=False)),
                ('otro_gato', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Formulario_Sin_Preferencias',
                'verbose_name_plural': 'Formularios_Sin_Preferencias',
                'db_table': 'Form_S_Prefer',
            },
        ),
    ]
