# Generated by Django 3.2.9 on 2022-01-14 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('MotorEmparejamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_s_preferencia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Form_SPref', to='usuario.usuarioreg'),
        ),
        migrations.AddField(
            model_name='form_c_preferencia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Form_CPref', to='usuario.usuarioreg'),
        ),
    ]
