# Generated by Django 3.2.9 on 2022-01-14 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import organizacion.models
import organizacion.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactoReferencia', models.IntegerField()),
                ('nomContactoRef', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('BUEN ADOPTANTE', 'BUEN ADOPTANTE'), ('MAL ADOPTANTE', 'MAL ADOPTANTE')], default='BUEN ADOPTANTE', max_length=255)),
                ('obsMalAdop', models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('DEVOLUCION DEL ANIMAL', 'DEVOLUCION DEL ANIMAL'), ('MALTRATO DEL ANIMAL', 'MALTRATO DEL ANIMAL'), ('ABANDONO DEL ANIMAL', 'ABANDONO DEL ANIMAL'), ('ABANDONO DEL SEGUIMIENTO', 'ABANDONO DEL SEGUIMIENTO'), ('OTRO', 'OTRO')], default='NINGUNO', max_length=255)),
                ('rangoEdad', models.CharField(choices=[('ADOLECENTE', 'ADOLECENTE'), ('JOVEN', 'JOVEN'), ('ADULTO JOVEN', 'ADULTO JOVEN'), ('ADULTEZ PRIMARIA', 'ADULTEZ PRIMARIA'), ('ADULTEZ INTERMEDIA', 'ADULTEZ INTERMEDIA'), ('ADULTEZ TARDIA', 'ADULTEZ TARDIA'), ('ADULTO MAYOR', 'ADULTO MAYOR')], max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('ocupacion', models.CharField(blank=True, max_length=255)),
                ('tipo_vivienda', models.CharField(choices=[('CASA PROPIA', 'CASA PROPIA'), ('CASA ALQUILER', 'CASA ALQUILER'), ('DEPARTAMENTO PROPIO', 'DEPARTAMENTO PROPIO'), ('DEPARTAMENTO ALQUILADO', 'DEPARTAMENTO ALQUILADO'), ('GARZONIER', 'GARZONIER'), ('OTRO', 'OTRO')], max_length=255)),
            ],
            options={
                'verbose_name': 'Adoptante',
                'verbose_name_plural': 'Adoptantes',
                'db_table': 'Adoptante',
            },
        ),
        migrations.CreateModel(
            name='AnimalesAdoptados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fechaRegistroAdop', models.DateField(default=datetime.datetime.now)),
                ('edad_Anim', models.CharField(choices=[('Cachorro Lactante', 'Cachorro Lactante (Hasta 2 Meses)'), ('Cachorro', 'Cachorro (Hasta 6 Meses)'), ('Joven', 'Joven (Hasta 3 - 4 Años)'), ('Adulto', 'Adulto (Hasta los 6-7 Años)'), ('Adulto Senior', 'Adulto Senior ( desde los 7 años para adelante)')], max_length=255)),
                ('edadAnos', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=0)),
                ('edadMeses', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0)),
                ('fotoAdopcion', models.ImageField(blank=True, null=True, upload_to=organizacion.upload.fotoAdopcion)),
                ('descripcionAdop', models.TextField(blank=True, default='Ingrese una descripcion de la adopcion')),
            ],
            options={
                'verbose_name': 'Animal Adoptado',
                'verbose_name_plural': 'Animales Adoptados',
                'db_table': 'AnimalesAdoptados',
            },
        ),
        migrations.CreateModel(
            name='AnimalesDatosB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(choices=[('VIVO', 'VIVO'), ('FALLECIDO', 'FALLECIDO')], default='VIVO', max_length=255)),
                ('estado', models.CharField(choices=[('REHABILITACION', 'REHABILITACION'), ('EN ADOPCION', 'EN ADOPCION'), ('ADOPTADO', 'ADOPTADO'), ('SANTUARIO', 'SANTUARIO')], default='REHABILITACION', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('fechaNaci', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tamano', models.CharField(choices=[('PEQUEÑO', 'PEQUEÑO'), ('MEDIANO', 'MEDIANO'), ('GRANDE', 'GRANDE'), ('GIGANTE', 'GIGANTE')], default='seleccione el tamaño', max_length=255)),
                ('sexo', models.CharField(choices=[('HEMBRA', 'HEMBRA'), ('MACHO', 'MACHO')], max_length=255)),
                ('descripcion', models.TextField(blank=True, default='Nin')),
            ],
            options={
                'verbose_name': 'Animal Datos Basicos',
                'verbose_name_plural': 'Animales Datos Basicos',
                'db_table': 'DatosBasicosAnimales',
            },
        ),
        migrations.CreateModel(
            name='AnimalesEnAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fecha_en_Adopcion', models.DateField(default=datetime.datetime.now)),
                ('edad_Anim', models.CharField(choices=[('Cachorro Lactante', 'Cachorro Lactante (Hasta 2 Meses)'), ('Cachorro', 'Cachorro (Hasta 6 Meses)'), ('Joven', 'Joven (Hasta 3 - 4 Años)'), ('Adulto', 'Adulto (Hasta los 6-7 Años)'), ('Adulto Senior', 'Adulto Senior ( desde los 7 años para adelante)')], max_length=255)),
                ('edadAnos', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=0)),
                ('edadMeses', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0)),
                ('fotoEnAdopcion', models.ImageField(blank=True, upload_to=organizacion.upload.fotoPaAdopcion)),
                ('desCaracter', models.TextField(blank=True)),
                ('desOrigen', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Animal En Adopcion',
                'verbose_name_plural': 'Animales en Adopcion',
                'db_table': 'AnimalesEnAdopcion',
            },
        ),
        migrations.CreateModel(
            name='AnimalesRescatados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('tipoIngreso', models.CharField(choices=[('RESCATE', 'RESCATE'), ('NACIDO EN LA ORGANIZACIÓN', 'NACIDO EN LA ORGANIZACIÓN'), ('ABANDONO EN CAMPAÑA/FERIA', 'ABANDONO EN CAMPAÑA/FERIA'), ('RECEPCION EN CAMPAÑA/FERIA', 'RECEPCION EN CAMPAÑA/FERIA'), ('AYUDA PARA ENCONTRAR HOGAR', 'AYUDA PARA ENCONTRAR HOGAR'), ('OTRO', 'OTRO')], default='RESCATE', max_length=100)),
                ('edad_Anim', models.CharField(blank=True, max_length=255)),
                ('edadAnos', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=0)),
                ('edadMeses', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0)),
                ('Fecha_Rescate', models.DateField(default=datetime.datetime.now)),
                ('FechaRegistro', models.DateField(default=datetime.datetime.now)),
                ('fotoRescate', models.ImageField(blank=True, upload_to=organizacion.upload.fotoIngreso)),
                ('descripcionRescate', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Animal Rescatado',
                'verbose_name_plural': 'Animales Rescatados',
                'db_table': 'AnimalesRescatados',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Color',
                'db_table': 'Color',
            },
        ),
        migrations.CreateModel(
            name='DocumentosAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('croquis', models.BooleanField(default=False)),
                ('docCroquis', models.FileField(blank=True, upload_to=organizacion.models.docAdopcion1)),
                ('servicio_basico', models.BooleanField(default=False)),
                ('docServicio', models.FileField(blank=True, upload_to=organizacion.models.docAdopcion1)),
                ('carnet', models.BooleanField(default=False)),
                ('docCarnet', models.FileField(blank=True, upload_to=organizacion.models.docAdopcion1)),
                ('compromiso', models.BooleanField(default=False)),
                ('docCompromiso', models.FileField(blank=True, upload_to=organizacion.models.docAdopcion1)),
                ('Otrodocumento', models.BooleanField(default=False)),
                ('docOtro', models.FileField(blank=True, upload_to=organizacion.models.docAdopcion1)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Documentos Adopcion',
                'verbose_name_plural': 'Documentos de Adopcion',
                'db_table': 'DocumentosAdopcion',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especies', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'db_table': 'Especie',
            },
        ),
        migrations.CreateModel(
            name='InfoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('fechaModificacion', models.DateField(auto_now_add=True)),
                ('tipoVacuna', models.CharField(blank=True, choices=[('NINGUNO', 'NINGUNO'), ('TRIPLE FELINA', 'TRIPLE FELINA'), ('TRIVALENTE', 'TRIVALENTED'), ('TETRAVALENTE', 'TETRAVALENTE'), ('PENTAVALENTE', 'PENTAVALENTE'), ('HEXAVALENTE', 'HEXAVALENTE'), ('HEPTAVALENTE', 'HEPTAVALENTE'), ('OCTOVALENTE', 'OCTOVALENTE')], default='NINGUNO', max_length=150)),
                ('ultimaFechaV', models.DateField(blank=True, null=True)),
                ('vacAntirrabica', models.BooleanField(default=False)),
                ('ultimaFechaReb', models.DateField(blank=True, null=True)),
                ('masInfoVac', models.TextField(blank=True, default='Ninguna')),
                ('desparacitacion', models.BooleanField(default=False)),
                ('ultimaFechaDes', models.DateField(blank=True, null=True)),
                ('masInfoDes', models.TextField(blank=True, default='Ninguna')),
                ('discapacidad', models.BooleanField(default=False)),
                ('Tipodiscapacidad', models.CharField(blank=True, choices=[('NINGUNO', 'NINGUNO'), ('FISICA', 'FISICA'), ('AUDITIVA', 'AUDITIVA'), ('VISUAL', 'VISUAL'), ('OLFATIVA', 'OLFAVITA'), ('VOCAL', 'VOCAL'), ('MULTIPLE', 'MULTIPLE')], default='NINGUNO', max_length=255)),
                ('masInfoDisca', models.TextField(blank=True, default='Ninguno')),
                ('probCAdultosM', models.BooleanField(default=True)),
                ('probCAdultos', models.BooleanField(default=True)),
                ('probCjovenes', models.BooleanField(default=True)),
                ('probCAdol', models.BooleanField(default=True)),
                ('probCNinosMenores', models.BooleanField(default=True)),
                ('probMujeres', models.BooleanField(default=True)),
                ('probHombres', models.BooleanField(default=True)),
                ('probSocialGatos', models.BooleanField(default=True)),
                ('probSocialPerros', models.BooleanField(default=True)),
                ('probSocialOtros', models.BooleanField(default=True)),
                ('masInfoProbSoc', models.TextField(blank=True, default='Ninguno')),
                ('moquillo', models.BooleanField(default=False)),
                ('parvovirus', models.BooleanField(default=False)),
                ('rabia', models.BooleanField(default=False)),
                ('cutaneaos', models.BooleanField(default=False)),
                ('parasitos', models.BooleanField(default=False)),
                ('desnutricion', models.BooleanField(default=False)),
                ('Depresion', models.BooleanField(default=False)),
                ('Ansiedad', models.BooleanField(default=False)),
                ('masInfoEnfer', models.TextField(blank=True, default='Ninguno')),
                ('esterilizacion', models.BooleanField(default=False)),
                ('fechaEster', models.DateField(blank=True, null=True)),
                ('codigoEster', models.CharField(blank=True, default=0, max_length=255)),
                ('gestacion', models.BooleanField(default=False)),
                ('infoGesta', models.TextField(blank=True)),
                ('lactancia', models.BooleanField(default=False)),
                ('infoLac', models.TextField(blank=True, max_length=255)),
                ('tipoAlim', models.CharField(blank=True, choices=[('NO SE CONOCE', 'NO SE CONOCE'), ('BALANCEADA', 'BALANCEADA'), ('CASERA', 'CASERA'), ('MIXTA', 'MIXTA'), ('OTROS', 'OTROS')], default='NO SE CONOCE', max_length=255)),
                ('descripcionEval', models.TextField(blank=True, default='Ninguna Observacion')),
            ],
            options={
                'verbose_name': 'Informe de Evaluacion',
                'verbose_name_plural': 'Informes de Evaluaciones',
                'db_table': 'InfoEvaluacion',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=255)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.especie', verbose_name='especies')),
            ],
            options={
                'verbose_name': 'raza',
                'verbose_name_plural': 'razas',
                'db_table': 'Raza',
            },
        ),
        migrations.CreateModel(
            name='AnimalesSantuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fechaIngresoSan', models.DateField()),
                ('edad_Anim', models.CharField(blank=True, choices=[('Cachorro Lactante', 'Cachorro Lactante (Hasta 2 Meses)'), ('Cachorro', 'Cachorro (Hasta 6 Meses)'), ('Joven', 'Joven (Hasta 3 - 4 Años)'), ('Adulto', 'Adulto (Hasta los 6-7 Años)'), ('Adulto Senior', 'Adulto Senior ( desde los 7 años para adelante)')], max_length=255)),
                ('edadAnos', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=0)),
                ('edadMeses', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=organizacion.upload.fotoSantuario)),
                ('nombreSantuario', models.CharField(max_length=255)),
                ('direccionSantuario', models.CharField(max_length=255)),
                ('nombreEncSan', models.CharField(max_length=255)),
                ('contactoRef', models.IntegerField()),
                ('descripcionSan', models.TextField(default='Ingrese informacion adicional')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacion.animalesdatosb')),
                ('datosMedicos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacion.infoevaluacion')),
            ],
            options={
                'verbose_name': 'Animal Santuario',
                'verbose_name_plural': 'Animales Santuario',
                'db_table': 'AnimalesSantuario',
            },
        ),
    ]
