# Generated by Django 3.2.9 on 2022-01-14 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalessantuario',
            name='voluntarioAcargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.voluntario'),
        ),
        migrations.AddField(
            model_name='animalesrescatados',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacion.animalesdatosb'),
        ),
        migrations.AddField(
            model_name='animalesrescatados',
            name='datosMedicos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datosMedicos', to='organizacion.infoevaluacion'),
        ),
        migrations.AddField(
            model_name='animalesrescatados',
            name='datosMedicos2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datosMedicos2', to='organizacion.infoevaluacion'),
        ),
        migrations.AddField(
            model_name='animalesrescatados',
            name='voluntarioAcargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.voluntario'),
        ),
        migrations.AddField(
            model_name='animalesenadopcion',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacion.animalesdatosb'),
        ),
        migrations.AddField(
            model_name='animalesenadopcion',
            name='datosMedicos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacion.infoevaluacion'),
        ),
        migrations.AddField(
            model_name='animalesenadopcion',
            name='voluntarioAcargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.voluntario'),
        ),
        migrations.AddField(
            model_name='animalesdatosb',
            name='color1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='organizacion.color'),
        ),
        migrations.AddField(
            model_name='animalesdatosb',
            name='color2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='organizacion.color'),
        ),
        migrations.AddField(
            model_name='animalesdatosb',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.especie'),
        ),
        migrations.AddField(
            model_name='animalesdatosb',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DatOrganizacion', to='usuario.organizacion'),
        ),
        migrations.AddField(
            model_name='animalesdatosb',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.raza'),
        ),
        migrations.AddField(
            model_name='animalesadoptados',
            name='adoptante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_adoptante', to='organizacion.adoptante'),
        ),
        migrations.AddField(
            model_name='animalesadoptados',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacion.animalesdatosb'),
        ),
        migrations.AddField(
            model_name='animalesadoptados',
            name='datosMedicos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacion.infoevaluacion'),
        ),
        migrations.AddField(
            model_name='animalesadoptados',
            name='documentos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacion.documentosadopcion'),
        ),
        migrations.AddField(
            model_name='animalesadoptados',
            name='voluntarioAcargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.voluntario'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.datospersonales'),
        ),
    ]
